# Generated by Django 3.2 on 2021-12-16 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardpin',
            options={'verbose_name': 'Связь пинов с доской', 'verbose_name_plural': 'Связь пинов с доской'},
        ),
        migrations.AlterField(
            model_name='boardpin',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.board', verbose_name='Доска'),
        ),
        migrations.AlterField(
            model_name='boardpin',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.pin', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='pins.PinCategory', verbose_name='Категория'),
        ),
    ]
